### ISSUE TITLE
Update composer

### ISSUE THREAD

**Issue by pdias** [Oryzone/OryzoneBoilerplateBundle#24]
Hello,

It's possible to update composer to use the latest version of jquery?

Thanks,

Paulo

**Comment by pquerner** [comment]
@pdias You could just update the block yourself. (With an online or offline src of your choice)
Read the documentation. :)

~Pascal

**Comment by lmammino** [comment]
Thanks @pdias and @pquerner !

I just updated jQuery to 1.11.2. 
Anyway if you want to use a different version you can extend the block `body_js_jquery` and change it however you want.

Regards

**Comment by lmammino** [comment]
I also updated the `composer.json` and removed the jQuery "upper bound" version check to allow you to use the `2.*` version if needed.
